In [3]:
import numpy as np

# Load the variable from memory
X = np.load('data/final_data/X_normalized.npy')
y = np.load('data/final_data/confirmed_normalized.npy')

# Print the loaded variable



In [6]:
X.shape

(30, 3218, 9)

In [13]:
y = y.reshape(30,3218,1)

In [14]:
y.shape

(30, 3218, 1)

In [15]:
data_all = np.concatenate((X, y), axis=2)

In [2]:
data_all.shape
import numpy as np

# Save data_all as .npy file
np.save('data/final_data/data_all.npy', data_all)


NameError: name 'data_all' is not defined

In [10]:
test = np.array([[1,2,3,4],[5,6,7,8]])
print(test)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
print(test.reshape(2,2,2))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
test=test.reshape(2,2,2)

In [16]:
test[0][0]

array([1, 2])